CREATE TABLE IF NOT EXISTS user_lanes
(
    id      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    lane_id UUID REFERENCES lanes (id) ON DELETE CASCADE ON UPDATE CASCADE
)